### ISSUE TITLE
New version fails W dynamax

### ISSUE THREAD

**Issue by xumical** [pmariglia/foul-play#210]
Opponet dynamaxed and used max airstream. Currently using MCTC for the battle bot.

WARNING  Unknown move maxairstream - using standard 0 priority move
INFO     Updated rayquaza's min speed to 74
INFO     Starting the volatile status dynamax on rayquaza
INFO     rayquaza started dynamax - doubling their HP to 438.40000000000003/548
WARNING  maxairstream is not a known move
INFO     rayquaza used two different moves - it cannot have a choice item
WARNING  Unknown move maxairstream - using standard 0 priority move
INFO     rayquaza did 92.64% damage to spiritomb with maxairstream
ERROR    Traceback (most recent call last):
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 96, in <module>
    asyncio.run(run_foul_play())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 79, in run_foul_play
    winner = await pokemon_battle(ps_websocket_client, FoulPlayConfig.pokemon_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\run_battle.py", line 265, in pokemon_battle
    action_required = await async_update_battle(battle, msg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2439, in async_update_battle
    return update_battle(battle, msg)
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2418, in update_battle
    update_dataset_possibilities(battle, damage_dealt, "damage_dealt")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2089, in update_dataset_possibilities
    or all_move_json[damage_dealt.move][constants.CATEGORY] == constants.STATUS
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'maxairstream'

Traceback (most recent call last):
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 96, in <module>
    asyncio.run(run_foul_play())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 79, in run_foul_play
    winner = await pokemon_battle(ps_websocket_client, FoulPlayConfig.pokemon_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\run_battle.py", line 265, in pokemon_battle
    action_required = await async_update_battle(battle, msg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2439, in async_update_battle
    return update_battle(battle, msg)
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2418, in update_battle
    update_dataset_possibilities(battle, damage_dealt, "damage_dealt")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2089, in update_dataset_possibilities
    or all_move_json[damage_dealt.move][constants.CATEGORY] == constants.STATUS
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'maxairstream'

**Comment by pmariglia** [comment]
bcfe9f98f8150fb010a72f857361f32934f576e3 should make it not crash but ymmv with gen6/7/8 as I have not been very focused on making those generations work. thnx for the issue

**Comment by xumical** [comment]
> [bcfe9f9](https://github.com/pmariglia/foul-play/commit/bcfe9f98f8150fb010a72f857361f32934f576e3) should make it not crash but ymmv with megas/z-moves/dynamax features in gen6/7/8 as I have not been very focused on making those work.
> 
> thnx for the issue

Thanks! I don't want to create a new issue but I experienced this while playing gen 9 blitz:

|turn|8
ERROR    Traceback (most recent call last):
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 96, in <module>
    asyncio.run(run_foul_play())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 79, in run_foul_play
    winner = await pokemon_battle(ps_websocket_client, FoulPlayConfig.pokemon_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\run_battle.py", line 265, in pokemon_battle
    action_required = await async_update_battle(battle, msg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2439, in async_update_battle
    return update_battle(battle, msg)
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2410, in update_battle
    function_to_call(battle, split_msg)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 486, in heal_or_damage
    pkmn.hp = pkmn.max_hp * new_hp_percentage
              ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'max_hp'

Traceback (most recent call last):
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 96, in <module>
    asyncio.run(run_foul_play())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\elibo\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\run.py", line 79, in run_foul_play
    winner = await pokemon_battle(ps_websocket_client, FoulPlayConfig.pokemon_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\run_battle.py", line 265, in pokemon_battle
    action_required = await async_update_battle(battle, msg)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2439, in async_update_battle
    return update_battle(battle, msg)
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 2410, in update_battle
    function_to_call(battle, split_msg)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elibo\Downloads\foul-play-main\foul-play-main\fp\battle_modifier.py", line 486, in heal_or_damage
    pkmn.hp = pkmn.max_hp * new_hp_percentage
              ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'max_hp'

**Comment by pmariglia** [comment]
In the future I'd actually prefer a separate issue simply to keep issues about one thing.

For your second issue it looks like the bot is unable to find the opponent's reserve pokemon by nickname when revival blessing is happening, but I am unable to reproduce locally. Do you have the logs leading up to this? Full logs of the entire battle if possible. The pokemon needs to be parsed by its nickname instead of its species ID so there's probably something wrong with either initially setting the pokemon's nickname or finding it in the reserve.

**Comment by xumical** [comment]
> In the future I'd actually prefer a separate issue simply to keep issues about one thing.
> 
> For your second issue it looks like the bot is unable to find the opponent's reserve pokemon by nickname when revival blessing is happening, but I am unable to reproduce locally. Do you have the logs leading up to this? Full logs of the entire battle if possible. The pokemon needs to be parsed by its nickname instead of its species ID so there's probably something wrong with either initially setting the pokemon's nickname or finding it in the reserve.

Thanks for the update! You can close this issue.

The first issue is no longer occurring, As for the second issue, if it happens again, I'll open a new issue and try to capture and provide the full logs
